<dependency>
  <groupId>com.santander.sgt.apm1953</groupId>
  <artifactId>sgt-apm1953-ppbm</artifactId>
  <version>1.0.1</version>
  <exclusions>
    <exclusion>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </exclusion>
    <exclusion>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </exclusion>
  </exclusions>
</dependency>
